"""Closed reason-code registry (§00 conventions / Appendix C): free-text
error strings are never load-bearing — only these SCREAMING_SNAKE constants
are, and every one of them traces to exactly one rule in §10.1."""

from __future__ import annotations

from enum import StrEnum


class ReasonCode(StrEnum):
    OK = "OK"
    CURRENCY_MISMATCH = "CURRENCY_MISMATCH"
    CATEGORY_NOT_ALLOWED = "CATEGORY_NOT_ALLOWED"
    MERCHANT_BLOCKED = "MERCHANT_BLOCKED"
    MANDATE_EXPIRED = "MANDATE_EXPIRED"
    MANDATE_NOT_YET_VALID = "MANDATE_NOT_YET_VALID"
    UNIT_CAP_EXCEEDED = "UNIT_CAP_EXCEEDED"
    BUDGET_EXCEEDED = "BUDGET_EXCEEDED"
    TXN_LIMIT_EXCEEDED = "TXN_LIMIT_EXCEEDED"
    QUANTITY_MISMATCH = "QUANTITY_MISMATCH"
    REFUND_POLICY_VIOLATION = "REFUND_POLICY_VIOLATION"
    PRICE_DRIFT = "PRICE_DRIFT"
    STALE_PRICE = "STALE_PRICE"
    INTENT_MISMATCH = "INTENT_MISMATCH"

    # §11.1 Money Action Gate (P6) — G1/G2/G4/G5/G6/G7 deny/flag codes not
    # already covered by the rule catalogue above.
    MANDATE_INVALID = "MANDATE_INVALID"
    MANDATE_TAMPERED = "MANDATE_TAMPERED"
    MANDATE_UNSIGNED = "MANDATE_UNSIGNED"
    MANDATE_REVOKED = "MANDATE_REVOKED"
    DECISION_STALE = "DECISION_STALE"
    QUOTE_EXPIRED = "QUOTE_EXPIRED"
    DUPLICATE_SUPPRESSED = "DUPLICATE_SUPPRESSED"
    AUDIT_UNAVAILABLE = "AUDIT_UNAVAILABLE"
    MALFORMED_REQUEST = "MALFORMED_REQUEST"
    PROVIDER_TRANSIENT = "PROVIDER_TRANSIENT"
    PROVIDER_TERMINAL = "PROVIDER_TERMINAL"
    PROVIDER_DECLINED = "PROVIDER_DECLINED"
    INTERNAL_ERROR = "INTERNAL_ERROR"
