"""§16: offline export bundle. `make bundle` runs this.

Produces a self-contained directory a third party can verify with nothing
but Python's standard library — no database, no network, no `actl` install,
no secret. `verify_bundle.py` inside the bundle is generated by literally
copying the source of domain/audit/{canonical,chain,merkle}.py into one
file: the "same implementation, mechanically copied for portability," not
a second, hand-written canonicaliser (§28 P3 instruction 1).
"""

from __future__ import annotations

import argparse
import asyncio
import hashlib
import json
from datetime import UTC, datetime
from pathlib import Path

from sqlalchemy.ext.asyncio import AsyncSession, async_sessionmaker

from actl.config import settings
from actl.infrastructure.db.uow import UnitOfWork

REPO_ROOT = Path(__file__).resolve().parents[1]
DOMAIN_AUDIT = REPO_ROOT / "src/actl/domain/audit"

_VERIFY_SCRIPT_HEADER = '''"""Standalone audit chain verifier.

Verifies audit_log.ndjson against checkpoints.json using nothing but the
Python standard library: no database, no network, no application package
import, no secret. The canonicalisation and hashing logic below mirrors
this project's own canonical.py/chain.py/merkle.py, copied verbatim at
export time — the same implementation, not a reimplementation.

Usage: python3 verify_bundle.py [bundle_dir]   (defaults to this script's own directory)
"""

from __future__ import annotations

import hashlib
import json
import sys
from pathlib import Path

'''

_VERIFY_SCRIPT_MAIN = '''

def _load_ndjson(path: Path) -> list[dict]:
    entries = []
    with path.open("r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if line:
                entries.append(json.loads(line))
    return entries


def _verify_manifest(bundle_dir: Path) -> bool:
    """§28 P10 instruction 5: file-level tamper evidence -- catches a
    swapped/corrupted/truncated evidence file *before* any chain-semantic
    check runs, independent of whether that swap happens to still look
    internally consistent. Only the raw evidence files are manifested
    (never verify_bundle.py itself -- a self-hash-check a compromised
    script could simply skip is no real protection)."""
    manifest_path = bundle_dir / "manifest.json"
    if not manifest_path.exists():
        print("MANIFEST MISSING: manifest.json not found in bundle")
        return False
    manifest = json.loads(manifest_path.read_text())
    for filename, expected_hash in manifest["files"].items():
        target = bundle_dir / filename
        if not target.exists():
            print(f"MANIFEST MISMATCH: {filename} listed in manifest but missing from bundle")
            return False
        actual_hash = "sha256:" + hashlib.sha256(target.read_bytes()).hexdigest()
        if actual_hash != expected_hash:
            print(f"MANIFEST MISMATCH: {filename}")
            print(f"  expected {expected_hash}")
            print(f"  computed {actual_hash}")
            return False
    print(f"manifest verified ({len(manifest['files'])} files) ........... ok")
    return True


def main() -> int:
    bundle_dir = Path(sys.argv[1]) if len(sys.argv) > 1 else Path(__file__).parent
    if not _verify_manifest(bundle_dir):
        return 1
    entries = _load_ndjson(bundle_dir / "audit_log.ndjson")
    checkpoints = json.loads((bundle_dir / "checkpoints.json").read_text())
    metadata = json.loads((bundle_dir / "metadata.json").read_text())
    checkpoints_by_to_seq = {c["to_seq"]: c for c in checkpoints}

    print(f"scanning {len(entries)} entries")

    if metadata["from_seq"] == 1:
        prev_hash = GENESIS_PREV_HASH
    else:
        # Partial export: nothing in this bundle independently proves what
        # came before from_seq, so the first entry's own claimed prev_hash
        # is trusted as the starting point rather than re-derived from
        # genesis. Full trustless verification requires from_seq == 1.
        print(
            f"NOTE: partial range (from_seq={metadata['from_seq']}) — chain start "
            "trusted from the bundle's own claim, not independently verified "
            "against genesis; export from seq=1 for full offline trust"
        )
        if entries:
            prev_hash = bytes.fromhex(entries[0]["prev_hash"][len("sha256:") :])
        else:
            prev_hash = GENESIS_PREV_HASH

    segment_hashes: list[bytes] = []
    expected_seq = metadata["from_seq"]

    for entry in entries:
        if entry["seq"] != expected_seq:
            print(f"CHAIN BROKEN at seq={expected_seq}")
            print("  expected: a row present")
            print(f"  computed: row missing (found seq={entry['seq']} instead)")
            return 1

        recomputed_hash = compute_entry_hash(prev_hash, entry["payload"])
        recomputed_hex = hex_prefixed(recomputed_hash)
        expected_prev_hex = hex_prefixed(prev_hash)
        if entry["prev_hash"] != expected_prev_hex or entry["entry_hash"] != recomputed_hex:
            print(f"CHAIN BROKEN at seq={entry['seq']}")
            print(f"  expected {entry['entry_hash']}")
            print(f"  computed {recomputed_hex}")
            print(f"entries {metadata['from_seq']}..{entry['seq'] - 1} verified intact")
            return 1

        segment_hashes.append(recomputed_hash)
        prev_hash = recomputed_hash
        expected_seq += 1

        checkpoint_every = metadata["checkpoint_every"]
        segment_start_seq = entry["seq"] - checkpoint_every + 1
        if entry["seq"] % checkpoint_every == 0 and segment_start_seq >= metadata["from_seq"]:
            checkpoint = checkpoints_by_to_seq.get(entry["seq"])
            if checkpoint is not None:
                segment = segment_hashes[-checkpoint_every:]
                recomputed_root = hex_prefixed(merkle_root(segment))
                if recomputed_root != checkpoint["merkle_root"]:
                    print(f"CHAIN BROKEN at seq={entry['seq']} (checkpoint)")
                    print(f"  expected {checkpoint['merkle_root']}")
                    print(f"  computed {recomputed_root}")
                    return 1
                print(f"merkle root matched at checkpoint {entry['seq']} ok")

    head = hex_prefixed(prev_hash) if entries else None
    if head != metadata["head_entry_hash"]:
        expected_head = metadata["head_entry_hash"]
        print(f"CHAIN BROKEN: head mismatch — expected {expected_head}, computed {head}")
        return 1

    from_seq, to_seq = metadata["from_seq"], metadata["to_seq"]
    print(f"recomputed {len(entries)} payload hashes .................. ok")
    print(f"recomputed {len(entries)} entry hashes .................... ok")
    print(f"sequence gapless ({from_seq}..{to_seq}) ....................... ok")
    print(f"CHAIN VALID   head={head}   entries={len(entries)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
'''


def _embed_module_source(path: Path) -> str:
    """Strip `from __future__ import annotations` and any `from actl....`
    import (the combined file supplies those symbols directly, inlined
    above) — everything else is copied verbatim."""
    lines = path.read_text().splitlines()
    kept = [
        line
        for line in lines
        if line.strip() != "from __future__ import annotations"
        and not line.startswith("from actl.")
    ]
    return "\n".join(kept)


def _build_verify_script() -> str:
    canonical_src = _embed_module_source(DOMAIN_AUDIT / "canonical.py")
    chain_src = _embed_module_source(DOMAIN_AUDIT / "chain.py")
    merkle_src = _embed_module_source(DOMAIN_AUDIT / "merkle.py")
    return (
        _VERIFY_SCRIPT_HEADER
        + "# ---- actl/domain/audit/canonical.py (verbatim) ----\n"
        + canonical_src
        + "\n\n# ---- actl/domain/audit/chain.py (verbatim) ----\n"
        + chain_src
        + "\n\n# ---- actl/domain/audit/merkle.py (verbatim) ----\n"
        + merkle_src
        + _VERIFY_SCRIPT_MAIN
    )


async def export_bundle(
    output_dir: Path,
    from_seq: int,
    to_seq: int,
    session_factory: async_sessionmaker[AsyncSession] | None = None,
) -> None:
    output_dir.mkdir(parents=True, exist_ok=True)

    async with UnitOfWork(session_factory) as uow:
        entries = await uow.audit_log.list_range(from_seq, to_seq)
        checkpoints = await uow.audit_checkpoints.list_all()

    # Only checkpoints whose *entire* segment is covered by the exported
    # range — a checkpoint whose segment starts before from_seq can't be
    # verified from this bundle alone (some of its entries aren't in it).
    relevant_checkpoints = [
        c for c in checkpoints if from_seq <= c.from_seq and c.to_seq <= to_seq
    ]

    ndjson_path = output_dir / "audit_log.ndjson"
    with ndjson_path.open("w", encoding="utf-8") as f:
        for entry in entries:
            row = {
                "seq": entry.seq,
                "ts": entry.ts.isoformat() if entry.ts else None,
                "trace_id": entry.trace_id,
                "actor_type": entry.actor_type,
                "actor_id": entry.actor_id,
                "action": entry.action,
                "subject": entry.subject,
                "payload": entry.payload,
                "payload_hash": entry.payload_hash,
                "prev_hash": entry.prev_hash,
                "entry_hash": entry.entry_hash,
            }
            f.write(json.dumps(row, sort_keys=True) + "\n")

    checkpoints_path = output_dir / "checkpoints.json"
    checkpoints_path.write_text(
        json.dumps(
            [
                {"from_seq": c.from_seq, "to_seq": c.to_seq, "merkle_root": c.merkle_root}
                for c in relevant_checkpoints
            ],
            indent=2,
        )
    )

    metadata_path = output_dir / "metadata.json"
    metadata_path.write_text(
        json.dumps(
            {
                "exported_at": datetime.now(UTC).isoformat(),
                "from_seq": from_seq,
                "to_seq": to_seq,
                "entry_count": len(entries),
                "head_entry_hash": entries[-1].entry_hash if entries else None,
                "checkpoint_every": settings.audit_checkpoint_every,
            },
            indent=2,
        )
    )

    (output_dir / "verify_bundle.py").write_text(_build_verify_script())

    # §28 P10 instruction 5: file-level tamper evidence for the three
    # evidence files -- never verify_bundle.py itself (see _verify_manifest's
    # own docstring in the embedded template for why a self-check is no
    # real protection).
    manifest_path = output_dir / "manifest.json"
    manifest_path.write_text(
        json.dumps(
            {
                "generated_at": datetime.now(UTC).isoformat(),
                "files": {
                    name: "sha256:" + hashlib.sha256((output_dir / name).read_bytes()).hexdigest()
                    for name in ("audit_log.ndjson", "checkpoints.json", "metadata.json")
                },
            },
            indent=2,
        )
    )


def main() -> None:
    parser = argparse.ArgumentParser(description="Export an offline-verifiable audit bundle")
    parser.add_argument("--out", type=Path, default=REPO_ROOT / "audit_bundle")
    parser.add_argument("--from", dest="from_seq", type=int, default=1)
    parser.add_argument("--to", dest="to_seq", type=int, required=True)
    args = parser.parse_args()

    asyncio.run(export_bundle(args.out, args.from_seq, args.to_seq))
    print(f"exported to {args.out}")


if __name__ == "__main__":
    main()
